# This file is an example logstash configuration you can use to set up a logstash server which works with the caQtDM LogstashLogHandler.

input {
  http {
    host => "127.0.0.1"
    port => 8080
    ssl_enabled => false
    # Codec fuer den Dateninput
    #additional_codecs => {}
    #codec => json { target => "[document]" }
  }
}

filter {
  mutate {
    add_field => {"job" => "logstash"}
    replace => { "type" => "stream"}
    remove_field => ["tags"]
  }

  if [caqtdm_events] {

    # save the ingest timestamp
    mutate {
      add_field => {"ingest_timestamp" => "%{@timestamp}"}
    }

    # caqtdm_events is an array, split it to generate single events
    split { field => "caqtdm_events" }

    # Use the provided timestamp as the main one
    date {
      match => ["[caqtdm_events][timestamp]", "ISO8601"]
      target => "@timestamp"
    }

    # Remove info about all events from the splitted parts
    mutate {
      remove_field => ["event"]
    }
  }

  ruby {
    code => '
      headers = event.get("[@metadata][input][http][request][headers]")
      if headers
        # normalize key names
        headers = headers.transform_keys { |k| k.downcase }

        client_ip = headers["x_forwarded_for"]

        # regular host.ip contains localhost due to nginx proxy, client_ip is actual client ip
        event.set("client_ip", client_ip) if client_ip
      end
    '
  }
}

output {
#  stdout {
#    codec => rubydebug
#  }

  elasticsearch {
    hosts => [""] # Enter your hosts here
    index => "logstash-caqtdm_%{+YYYY.MM}"
    user => "" # Enter your username here
    password => "" # Enter your password here
   # ssl => true
   # cacert => "" # optional cert location
   ssl_certificate_authorities => "" # enter your cert auth here

  }

  loki {
    url => "http://localhost:3100/loki/api/v1/push"
    batch_size => 10
    message_field => "message"
  }
}
